name: mass-spec
channels: 
- conda-forge
dependencies:
  - python=3.12
  - ipykernel
  - jupyter
  - jupytext
  - pip
  # Data Science Packages
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - networkx
  # Chemistry Packages
  - rdkit
  # ML Packages
  - pytorch
  - torch-geometric
  - scikit-optimize
  - scikit-learn
  - tensorflow
  - keras
  # Testing
  - pytest
  - pytest-cov